# Generated by Django 4.0 on 2021-12-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mfy_task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='mfy_users',
            fields=[
                ('user_phone_no', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_loc.mfy_task')),
            ],
        ),
    ]
